repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: ''  # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
        exclude: migrations
  - repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3.8 # Should be a command that runs python3.6+
